name: nodejs CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clonando app
        uses: actions/checkout@v3

      - name: configurando nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: instalar paquetes
        run: npm ci

      - name: ejecutar linter
        run: npm run lint
      
      - name: ejecutar tests
        run: npm test